# Add groups to the config as shown below.
# Format: - GroupName:Color,Bold/Italic/etc,Bold/Italic, etc.
# Only 1 Color can be used and must be the first word.
# Use all caps when specifying.
groupandcolor:
  - Admin:RED
  - Example1:GREEN,BOLD
  - Example2:BLUE,BOLD,ITALIC