name: BuxCommands
main: net.buxville.rahman.buxcommands.BuxCommands
version: 1
commands:
   acc:
      description: accept command
   den:
      description: deny command
   getrank:
      description: getrank command
   groll:
      description: groll command
   hat:
      description: hat command
   tpahere:
      description: tpa command
   tpchere:
      description: tpc command
   tpcto:
      description: tpcto command
   who:
      description: who command
   whohide:
      description: whohide command
   w:
      description: whisper command
   whisper:
      description: whisper command
   r:
      description: whisper reply command
   reply:
      description: whisper reply command
   forcechannel:
      description: forcechannel command
permissions:
   buxcommands.groll:
     description: Gives access to groll command
   buxcommands.hat:
     description: Gives access to hat command
   buxcommands.tpa:
     description: Gives access to tpa command
   buxcommands.tpc:
     description: Gives access to tpc command
   buxcommands.tpcto:
     description: Gives access to tpc command
   buxcommands.whohide:
     description: Gives access to whohide command
   buxcommands.whisper:
     description: Gives access to whisper command
   buxcommands.reply:
     description: Gives access to whisper reply command
   buxcommands.forcechannel:
     description: Gives access to forcechannel command
