name: BuxCommands
main: net.buxville.rahman.buxcommands.BuxCommands
version: 0.8.2
commands:
   acc:
      description: accept command
   den:
      description: deny command
   getrank:
      description: getrank command
   groll:
      description: groll command
   hat:
      description: hat command
   tpahere:
      description: tpa command
   tpchere:
      description: tpc command
   tpcto:
      description: tpcto command
   who:
      description: who command
   whohide:
      description: whohide command
permissions:
   buxcommands.groll:
     description: Gives access to groll command
   buxcommands.hat:
     description: Gives access to hat command
   buxcommands.tpa:
     description: Gives access to tpa command
   buxcommands.tpc:
     description: Gives access to tpc command
   buxcommands.tpcto:
     description: Gives access to tpc command
   buxcommands.whohide:
     description: Gives access to whohide command